import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer"

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica", fontSize: 12 },
  header: { fontSize: 22, marginBottom: 4, fontWeight: "bold" },
  subtitle: { fontSize: 10, color: "#999", marginBottom: 24 },
  row: { flexDirection: "row", justifyContent: "space-between", marginBottom: 10, paddingBottom: 8, borderBottom: "1 solid #f0f0f0" },
  label: { color: "#666", fontSize: 11 },
  value: { fontWeight: "bold", fontSize: 11 },
  divider: { borderBottom: "2 solid #eee", marginVertical: 16 },
  footer: { marginTop: 40, fontSize: 9, color: "#aaa", textAlign: "center" },
})

interface ReceiptProps {
  receiptId: string
  unitNumber: string
  amount: string
  paymentMethod: string
  billingPeriod: string
  date: string
  status: string
}

export function ReceiptDocument({
  receiptId,
  unitNumber,
  amount,
  paymentMethod,
  billingPeriod,
  date,
  status,
}: ReceiptProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.header}>Payment Receipt</Text>
        <Text style={styles.subtitle}>RentalMgmt</Text>
        <View style={styles.divider} />
        <View style={styles.row}>
          <Text style={styles.label}>Receipt #</Text>
          <Text style={styles.value}>{receiptId.slice(0, 8).toUpperCase()}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Unit</Text>
          <Text style={styles.value}>{unitNumber}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Amount</Text>
          <Text style={styles.value}>{amount}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Payment Method</Text>
          <Text style={styles.value}>{paymentMethod}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Billing Period</Text>
          <Text style={styles.value}>{billingPeriod}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Date</Text>
          <Text style={styles.value}>{date}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Status</Text>
          <Text style={styles.value}>{status}</Text>
        </View>
        <View style={styles.divider} />
        <Text style={styles.footer}>
          This receipt was generated by RentalMgmt. Keep for your records.
        </Text>
      </Page>
    </Document>
  )
}
